package com.matawan.NiceFCManager.enumeration;

public enum PlayerPosition {
    
    GARDIEN_DE_BUT,
    ARRIERE_DROIT,
    ARRIERE_GAUCHE,
    ARRIERE_CENTRAL,
    MILIEU_DE_TERRAIN_DEFENSIF,
    MILIEU_DE_TERRAIN_DROIT,
    MILIEU_DE_TERRAIN_CENTRAL,
    ATTAQUANT,
    MILIEU_DE_TERRAIN_OFFENSIF,
    MILIEU_DE_TERRAIN_GAUCHE;
}
